[package]
name = "viper"
version = "0.1.0"
edition = "2021"

[dependencies]
duchess = { path = "../.." }
jni = { version = "0.21.1", features = ["invocation"] }
once_cell = "1.17.1"

[build-dependencies]
ureq = "2.1"
zip = "0.5"
zip-extensions = "0.6"
