[workspace]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nikomatsakis/duchess"

[package]
name = "duchess"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "Experiments with Java-Rust interop"

[dependencies]
duchess-macro = { path = "macro" }
jni = "0.21.1"
