[package]
name = "duchess"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nikomatsakis/duchess"
description = "Experiments with Java-Rust interop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
lalrpop-util = { version = "0.19.9", features = ["lexer"] }
regex = "1"

[build-dependencies]
lalrpop = "0.19.9"

[dev-dependencies]
expect-test = "1.4.1"
