[package]
name = "duchess"
version = "0.1.0"
edition = "2021"
license = "MIT OR APACHE-2.0"
repository = "https://github.com/nikomatsakis/duchess"
description = "Experiments with Java-Rust interop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
