name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Build
      run: cargo build --verbose
    - name: Test crates
      run: cargo test --all-targets --verbose
    - name: Test client crates
      run: cargo test --all-targets --verbose --manifest-path=test-crates/Cargo.toml
